// Disclosure: Portions of this unit test have been generated by ChatGPT
using UnityEngine;
using NUnit.Framework;
using UnityEngine.TestTools;
using System.Collections;

public class MapGeneratorTests
{
    [UnityTest]
    public IEnumerator TestMapGeneration()
    {
        // Create a test GameObject to hold the MapGenerator script
        GameObject testObject = new GameObject();
        MapGenerator mapGenerator = testObject.AddComponent<MapGenerator>();

        // Mock tile prefab
        GameObject tilePrefab = new GameObject("TilePrefab");
        mapGenerator.tilePrefab = tilePrefab;

        // Create a test map
        int[,] testMap = 
        {
            {1, 1, 1, 1, 0},
            {1, 1, 1, 1, 0},
            {1, 1, 1, 1, 1},
            {0, 1, 1, 1, 1},
            {0, 1, 1, 1, 0}
        };

        // Simulate Start() method being called implicitly
        yield return null;

        // Check if the tile array is set correctly
        Assert.AreEqual(testMap, mapGenerator.GetArray());

        // Check if the tiles are instantiated correctly
        Tile[] tiles = testObject.GetComponentsInChildren<Tile>();
        Assert.AreEqual(16, tiles.Length); // Assuming each '1' in the test map generates a tile

        // Clean up
        GameObject.Destroy(testObject);
    }
}
