// Disclosure: Portions of this unit test have been generated by ChatGPT
using UnityEngine;
using NUnit.Framework;

public class MapGeneratorTests
{
    public GameObject tileGO;
    public MapGenerator mapGenerator;
    public int[,] testMap;
    public int[,] defaultMap;
    public int[,] ownerArray;

    [SetUp]
    public void SetUp()
    {
        tileGO = new GameObject("Tile");
        mapGenerator = tileGO.AddComponent<MapGenerator>();
        mapGenerator.tilePrefab = new GameObject("Tile");
        mapGenerator.tilePrefab.AddComponent<Tile>();

        defaultMap = new int[2, 2]
        {
            {1, 1},
            {1, 1}
        };
        ownerArray = new int[2, 2]
        {
            {1, 0},
            {0, 0}
        };
        testMap = new int[4, 2]
        {
            {1, 1},
            {1, 1},
            {1, 1},
            {1, 1}
        };   
    }

    [Test]
    public void MapGenerator_TestSetArray()
    {
        mapGenerator.SetArray(defaultMap);
        Assert.AreEqual(defaultMap, mapGenerator.GetArray());
    }
    
    [Test]
    public void MapGenerator_TestSetOwner()
    {
        mapGenerator.SetOwner(ownerArray);
        Assert.AreEqual(ownerArray, mapGenerator.GetOwnership());
    }

    [Test]
    public void MapGenerator_TestCreateSymmetricMap()
    {
        mapGenerator.SetOwner(ownerArray);
        mapGenerator.SetArray(defaultMap);
        mapGenerator.CreateSymmetricMap(defaultMap);
        Assert.AreEqual(testMap, mapGenerator.GetArray());
    }

    [Test]
    public void MapGenerator_TestGetOwnership()
    {
        mapGenerator.SetOwner(ownerArray);
        Assert.AreEqual(ownerArray, mapGenerator.GetOwnership());
    }
}