// Disclosure: Portions of this unit test have been generated by ChatGPT
using UnityEngine;
using NUnit.Framework;

public class MapGeneratorTests
{
    [Test]
    public void TestMapGeneration()
    {
        // Create a test GameObject to hold the MapGenerator script
        GameObject testObject = new GameObject();
        MapGenerator mapGenerator = testObject.AddComponent<MapGenerator>();

        // Create a test map
        int[,] testMap = 
        {
            {1, 1, 1, 1, 0},
            {1, 1, 1, 1, 0},
            {1, 1, 1, 1, 1},
            {0, 1, 1, 1, 1},
            {0, 1, 1, 1, 0}
        };

        // Set the test map
        mapGenerator.SetArray(testMap);
        mapGenerator.CreateSymmetricMap(testMap);
        mapGenerator.GenerateMap();

        // Check if the tiles are instantiated correctly
        Tile[] tiles = testObject.GetComponentsInChildren<Tile>();
        Assert.AreEqual(16, tiles.Length); // Assuming each '1' in the test map generates a tile
    }
}
